
username=aabbcc
password=Ab@12

URL1=https://webdriveruniversity.com/Login-Portal/index.html
URL2=https://webdriveruniversity.com/Click-Buttons/index.html
URL3=https://webdriveruniversity.com/Dropdown-Checkboxes-RadioButtons/index.html
URL4=https://webdriveruniversity.com/Actions/index.html
URL5=https://webdriveruniversity.com/Scrolling/index.html
URL6=https://www.webdriveruniversity.com/Hidden-Elements/index.html